#!/bin/bash
# Quick Start Commands - Run These to Test the Bot

echo "========================================================================"
echo "  Cryptography Fix Complete! ✅"
echo "========================================================================"
echo ""
echo "✅ Docker images rebuilt and pushed to ECR"
echo "✅ Cryptography 50.0.1 installed and verified"
echo "✅ JWT RSA signing working"
echo "✅ ECS services updated (currently scaled to 0)"
echo ""
echo "========================================================================"
echo "  OPTION 1: Scale Up AWS ECS Services"
echo "========================================================================"
echo ""
echo "# Scale up worker"
echo "aws ecs update-service --cluster SlackAgentCluster --service slack-agent-worker --desired-count 1 --region us-east-2"
echo ""
echo "# Scale up bot"
echo "aws ecs update-service --cluster SlackAgentCluster --service slack-agent-bot --desired-count 1 --region us-east-2"
echo ""
echo "# Monitor status"
echo "aws ecs describe-services --cluster SlackAgentCluster --services slack-agent-worker slack-agent-bot --region us-east-2 --query 'services[].[serviceName,status,runningCount,desiredCount]' --output table"
echo ""
echo "========================================================================"
echo "  OPTION 2: Run Locally for Testing"
echo "========================================================================"
echo ""
echo "cd /Users/chinmayabharadwajhs/@Slash/slack-coding-agent"
echo "source venv/bin/activate"
echo "pip install cryptography>=41.0.0  # if not already installed"
echo ""
echo "# Terminal 1: Start bot"
echo "python -m slackagent.main"
echo ""
echo "# Terminal 2: Start worker"
echo "python -m slackagent.worker"
echo ""
echo "========================================================================"
echo "  Test in Slack"
echo "========================================================================"
echo ""
echo "Send this message in any channel where the bot is invited:"
echo ""
echo "  @codingbot owner/test-repo Add a simple TODO comment to README.md"
echo ""
echo "Expected flow:"
echo "  1. Bot acknowledges task"
echo "  2. Planning phase completes"
echo "  3. Implementation phase completes"
echo "  4. GitHub PR created successfully"
echo ""
echo "========================================================================"
echo "  Verify Images in ECR"
echo "========================================================================"
echo ""
echo "aws ecr describe-images --repository-name slack-agent-sandbox --image-ids imageTag=latest --region us-east-2"
echo "aws ecr describe-images --repository-name slack-coding-agent --image-ids imageTag=latest --region us-east-2"
echo ""
echo "========================================================================"
echo "  Test Cryptography in Container"
echo "========================================================================"
echo ""
echo "docker run --rm 958357664308.dkr.ecr.us-east-2.amazonaws.com/slack-agent-sandbox:latest python -c \"import cryptography; print(cryptography.__version__)\""
echo ""
echo "========================================================================"
echo "  Documentation"
echo "========================================================================"
echo ""
echo "  CRYPTOGRAPHY-FIX.md      - Detailed guide (430 lines)"
echo "  QUICK-REF.md             - Quick reference"
echo "  COMPLETION-SUMMARY.md    - What was done"
echo "  quick-start.sh           - This file"
echo ""
echo "========================================================================"
